export enum TodoActivityType {
  TASK_CREATED = 'TASK_CREATED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_MOVED = 'TASK_MOVED',
  TASK_DELETED = 'TASK_DELETED',
  JIRA_LINKED = 'JIRA_LINKED',
  JIRA_UNLINKED = 'JIRA_UNLINKED',
  JIRA_SYNCED = 'JIRA_SYNCED',
  JIRA_SYNC_PENDING = 'JIRA_SYNC_PENDING',
  JIRA_SYNC_FAILED = 'JIRA_SYNC_FAILED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  COMMENT_UPDATED = 'COMMENT_UPDATED',
  COMMENT_DELETED = 'COMMENT_DELETED',
}
