services:
  nestjs-boilerplate-api:
    image: nestjs-boilerplate-api
    container_name: nestjs-boilerplate-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    networks:
      - nestjs-boilerplate-network

  db:
    image: postgres:16
    container_name: nestjs-boilerplate-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nestjs_boilerplate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "UTC"
    ports:
      - "25432:5432"
    networks:
      - nestjs-boilerplate-network

  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    environment:
      REDIS_ARGS: "--requirepass redispass"
    networks:
      - nestjs-boilerplate-network

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025
    networks:
      - nestjs-boilerplate-network

  # Text Embeddings Inference - BAAI/bge-m3
  tei:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest
    container_name: nestjs-boilerplate-tei
    restart: always
    ports:
      - "8080:80"
    volumes:
      - tei_model_data:/data
    command: --model-id BAAI/bge-m3
    networks:
      - nestjs-boilerplate-network


volumes:
  postgres_data:
  redis_data:
  tei_model_data:

networks:
  nestjs-boilerplate-network:
    driver: bridge
