services:
  todo-rag-api:
    image: todo-rag-api
    # Only for Production server
    platform: linux/arm64
    container_name: todo-rag-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - todo-rag-network
      - proxy

  migrate:
    image: todo-rag-api
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ['npm', 'run', 'migration:prod:up']
    depends_on:
      db:
        condition: service_started
    networks:
      - todo-rag-network
      - proxy
    restart: 'no'

  db:
    image: pgvector/pgvector:pg18
    platform: linux/arm64
    container_name: todo-rag-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
      # Mount a script to automatically enable the extension on startup
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: 'UTC'
    ports:
      - '127.0.0.1:5432:5432'
    networks:
      - todo-rag-network

  redis:
    image: redis/redis-stack:latest
    platform: linux/arm64
    container_name: todo-rag-redis
    restart: always
    command: >
      redis-server
      --appendonly yes
      --requirepass ${REDIS_PASSWORD}

    volumes:
      - redis_data:/data

    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', 'PING']
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - todo-rag-network

volumes:
  postgres_data:
  redis_data:

networks:
  # For cloudflare tunnel to access the API container
  proxy:
    external: true
  todo-rag-network:
    driver: bridge
