export enum AiIntent {
  TASK_CREATE = 'TASK_CREATE',
  TASK_UPDATE = 'TASK_UPDATE',
  TASK_DELETE = 'TASK_DELETE',
  TASK_SEARCH = 'TASK_SEARCH',
  PROJECT_MANAGE = 'PROJECT_MANAGE',
  COMMENT_CREATE = 'COMMENT_CREATE',
  COMMENT_SEARCH = 'COMMENT_SEARCH',
  TAG_MANAGE = 'TAG_MANAGE',
  STATUS_UPDATE = 'STATUS_UPDATE',
  DASHBOARD_QUERY = 'DASHBOARD_QUERY',
  STANDUP_REPORT = 'STANDUP_REPORT',
  TODO_HELP = 'TODO_HELP',
  OUT_OF_SCOPE = 'OUT_OF_SCOPE',
  AMBIGUOUS = 'AMBIGUOUS',
}

export const AI_INTENT_VALUES = Object.values(AiIntent) as [
  AiIntent,
  ...AiIntent[],
];
